// <auto-generated />
using System;
using DataAccessLayer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(S3DbContext))]
    partial class S3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Model.Building", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Location = "Location_1",
                            Name = "Building_Name_1"
                        },
                        new
                        {
                            Id = (short)2,
                            Location = "Location_2",
                            Name = "Building_Name_2"
                        },
                        new
                        {
                            Id = (short)3,
                            Location = "Location_3",
                            Name = "Building_Name_3"
                        },
                        new
                        {
                            Id = (short)4,
                            Location = "Location_4",
                            Name = "Building_Name_4"
                        },
                        new
                        {
                            Id = (short)5,
                            Location = "Location_5",
                            Name = "Building_Name_5"
                        },
                        new
                        {
                            Id = (short)6,
                            Location = "Location_6",
                            Name = "Building_Name_6"
                        },
                        new
                        {
                            Id = (short)7,
                            Location = "Location_7",
                            Name = "Building_Name_7"
                        },
                        new
                        {
                            Id = (short)8,
                            Location = "Location_8",
                            Name = "Building_Name_8"
                        },
                        new
                        {
                            Id = (short)9,
                            Location = "Location_9",
                            Name = "Building_Name_9"
                        },
                        new
                        {
                            Id = (short)10,
                            Location = "Location_10",
                            Name = "Building_Name_10"
                        },
                        new
                        {
                            Id = (short)11,
                            Location = "Location_11",
                            Name = "Building_Name_11"
                        },
                        new
                        {
                            Id = (short)12,
                            Location = "Location_12",
                            Name = "Building_Name_12"
                        },
                        new
                        {
                            Id = (short)13,
                            Location = "Location_13",
                            Name = "Building_Name_13"
                        },
                        new
                        {
                            Id = (short)14,
                            Location = "Location_14",
                            Name = "Building_Name_14"
                        },
                        new
                        {
                            Id = (short)15,
                            Location = "Location_15",
                            Name = "Building_Name_15"
                        },
                        new
                        {
                            Id = (short)16,
                            Location = "Location_16",
                            Name = "Building_Name_16"
                        },
                        new
                        {
                            Id = (short)17,
                            Location = "Location_17",
                            Name = "Building_Name_17"
                        },
                        new
                        {
                            Id = (short)18,
                            Location = "Location_18",
                            Name = "Building_Name_18"
                        },
                        new
                        {
                            Id = (short)19,
                            Location = "Location_19",
                            Name = "Building_Name_19"
                        },
                        new
                        {
                            Id = (short)20,
                            Location = "Location_20",
                            Name = "Building_Name_20"
                        },
                        new
                        {
                            Id = (short)21,
                            Location = "Location_21",
                            Name = "Building_Name_21"
                        },
                        new
                        {
                            Id = (short)22,
                            Location = "Location_22",
                            Name = "Building_Name_22"
                        },
                        new
                        {
                            Id = (short)23,
                            Location = "Location_23",
                            Name = "Building_Name_23"
                        },
                        new
                        {
                            Id = (short)24,
                            Location = "Location_24",
                            Name = "Building_Name_24"
                        },
                        new
                        {
                            Id = (short)25,
                            Location = "Location_25",
                            Name = "Building_Name_25"
                        },
                        new
                        {
                            Id = (short)26,
                            Location = "Location_26",
                            Name = "Building_Name_26"
                        },
                        new
                        {
                            Id = (short)27,
                            Location = "Location_27",
                            Name = "Building_Name_27"
                        },
                        new
                        {
                            Id = (short)28,
                            Location = "Location_28",
                            Name = "Building_Name_28"
                        },
                        new
                        {
                            Id = (short)29,
                            Location = "Location_29",
                            Name = "Building_Name_29"
                        },
                        new
                        {
                            Id = (short)30,
                            Location = "Location_30",
                            Name = "Building_Name_30"
                        },
                        new
                        {
                            Id = (short)31,
                            Location = "Location_31",
                            Name = "Building_Name_31"
                        },
                        new
                        {
                            Id = (short)32,
                            Location = "Location_32",
                            Name = "Building_Name_32"
                        },
                        new
                        {
                            Id = (short)33,
                            Location = "Location_33",
                            Name = "Building_Name_33"
                        },
                        new
                        {
                            Id = (short)34,
                            Location = "Location_34",
                            Name = "Building_Name_34"
                        },
                        new
                        {
                            Id = (short)35,
                            Location = "Location_35",
                            Name = "Building_Name_35"
                        },
                        new
                        {
                            Id = (short)36,
                            Location = "Location_36",
                            Name = "Building_Name_36"
                        },
                        new
                        {
                            Id = (short)37,
                            Location = "Location_37",
                            Name = "Building_Name_37"
                        },
                        new
                        {
                            Id = (short)38,
                            Location = "Location_38",
                            Name = "Building_Name_38"
                        },
                        new
                        {
                            Id = (short)39,
                            Location = "Location_39",
                            Name = "Building_Name_39"
                        },
                        new
                        {
                            Id = (short)40,
                            Location = "Location_40",
                            Name = "Building_Name_40"
                        },
                        new
                        {
                            Id = (short)41,
                            Location = "Location_41",
                            Name = "Building_Name_41"
                        },
                        new
                        {
                            Id = (short)42,
                            Location = "Location_42",
                            Name = "Building_Name_42"
                        },
                        new
                        {
                            Id = (short)43,
                            Location = "Location_43",
                            Name = "Building_Name_43"
                        },
                        new
                        {
                            Id = (short)44,
                            Location = "Location_44",
                            Name = "Building_Name_44"
                        },
                        new
                        {
                            Id = (short)45,
                            Location = "Location_45",
                            Name = "Building_Name_45"
                        },
                        new
                        {
                            Id = (short)46,
                            Location = "Location_46",
                            Name = "Building_Name_46"
                        },
                        new
                        {
                            Id = (short)47,
                            Location = "Location_47",
                            Name = "Building_Name_47"
                        },
                        new
                        {
                            Id = (short)48,
                            Location = "Location_48",
                            Name = "Building_Name_48"
                        },
                        new
                        {
                            Id = (short)49,
                            Location = "Location_49",
                            Name = "Building_Name_49"
                        },
                        new
                        {
                            Id = (short)50,
                            Location = "Location_50",
                            Name = "Building_Name_50"
                        },
                        new
                        {
                            Id = (short)51,
                            Location = "Location_51",
                            Name = "Building_Name_51"
                        },
                        new
                        {
                            Id = (short)52,
                            Location = "Location_52",
                            Name = "Building_Name_52"
                        },
                        new
                        {
                            Id = (short)53,
                            Location = "Location_53",
                            Name = "Building_Name_53"
                        },
                        new
                        {
                            Id = (short)54,
                            Location = "Location_54",
                            Name = "Building_Name_54"
                        },
                        new
                        {
                            Id = (short)55,
                            Location = "Location_55",
                            Name = "Building_Name_55"
                        },
                        new
                        {
                            Id = (short)56,
                            Location = "Location_56",
                            Name = "Building_Name_56"
                        },
                        new
                        {
                            Id = (short)57,
                            Location = "Location_57",
                            Name = "Building_Name_57"
                        },
                        new
                        {
                            Id = (short)58,
                            Location = "Location_58",
                            Name = "Building_Name_58"
                        },
                        new
                        {
                            Id = (short)59,
                            Location = "Location_59",
                            Name = "Building_Name_59"
                        },
                        new
                        {
                            Id = (short)60,
                            Location = "Location_60",
                            Name = "Building_Name_60"
                        },
                        new
                        {
                            Id = (short)61,
                            Location = "Location_61",
                            Name = "Building_Name_61"
                        },
                        new
                        {
                            Id = (short)62,
                            Location = "Location_62",
                            Name = "Building_Name_62"
                        },
                        new
                        {
                            Id = (short)63,
                            Location = "Location_63",
                            Name = "Building_Name_63"
                        },
                        new
                        {
                            Id = (short)64,
                            Location = "Location_64",
                            Name = "Building_Name_64"
                        },
                        new
                        {
                            Id = (short)65,
                            Location = "Location_65",
                            Name = "Building_Name_65"
                        },
                        new
                        {
                            Id = (short)66,
                            Location = "Location_66",
                            Name = "Building_Name_66"
                        },
                        new
                        {
                            Id = (short)67,
                            Location = "Location_67",
                            Name = "Building_Name_67"
                        },
                        new
                        {
                            Id = (short)68,
                            Location = "Location_68",
                            Name = "Building_Name_68"
                        },
                        new
                        {
                            Id = (short)69,
                            Location = "Location_69",
                            Name = "Building_Name_69"
                        },
                        new
                        {
                            Id = (short)70,
                            Location = "Location_70",
                            Name = "Building_Name_70"
                        },
                        new
                        {
                            Id = (short)71,
                            Location = "Location_71",
                            Name = "Building_Name_71"
                        },
                        new
                        {
                            Id = (short)72,
                            Location = "Location_72",
                            Name = "Building_Name_72"
                        },
                        new
                        {
                            Id = (short)73,
                            Location = "Location_73",
                            Name = "Building_Name_73"
                        },
                        new
                        {
                            Id = (short)74,
                            Location = "Location_74",
                            Name = "Building_Name_74"
                        },
                        new
                        {
                            Id = (short)75,
                            Location = "Location_75",
                            Name = "Building_Name_75"
                        },
                        new
                        {
                            Id = (short)76,
                            Location = "Location_76",
                            Name = "Building_Name_76"
                        },
                        new
                        {
                            Id = (short)77,
                            Location = "Location_77",
                            Name = "Building_Name_77"
                        },
                        new
                        {
                            Id = (short)78,
                            Location = "Location_78",
                            Name = "Building_Name_78"
                        },
                        new
                        {
                            Id = (short)79,
                            Location = "Location_79",
                            Name = "Building_Name_79"
                        },
                        new
                        {
                            Id = (short)80,
                            Location = "Location_80",
                            Name = "Building_Name_80"
                        },
                        new
                        {
                            Id = (short)81,
                            Location = "Location_81",
                            Name = "Building_Name_81"
                        },
                        new
                        {
                            Id = (short)82,
                            Location = "Location_82",
                            Name = "Building_Name_82"
                        },
                        new
                        {
                            Id = (short)83,
                            Location = "Location_83",
                            Name = "Building_Name_83"
                        },
                        new
                        {
                            Id = (short)84,
                            Location = "Location_84",
                            Name = "Building_Name_84"
                        },
                        new
                        {
                            Id = (short)85,
                            Location = "Location_85",
                            Name = "Building_Name_85"
                        },
                        new
                        {
                            Id = (short)86,
                            Location = "Location_86",
                            Name = "Building_Name_86"
                        },
                        new
                        {
                            Id = (short)87,
                            Location = "Location_87",
                            Name = "Building_Name_87"
                        },
                        new
                        {
                            Id = (short)88,
                            Location = "Location_88",
                            Name = "Building_Name_88"
                        },
                        new
                        {
                            Id = (short)89,
                            Location = "Location_89",
                            Name = "Building_Name_89"
                        },
                        new
                        {
                            Id = (short)90,
                            Location = "Location_90",
                            Name = "Building_Name_90"
                        },
                        new
                        {
                            Id = (short)91,
                            Location = "Location_91",
                            Name = "Building_Name_91"
                        },
                        new
                        {
                            Id = (short)92,
                            Location = "Location_92",
                            Name = "Building_Name_92"
                        },
                        new
                        {
                            Id = (short)93,
                            Location = "Location_93",
                            Name = "Building_Name_93"
                        },
                        new
                        {
                            Id = (short)94,
                            Location = "Location_94",
                            Name = "Building_Name_94"
                        },
                        new
                        {
                            Id = (short)95,
                            Location = "Location_95",
                            Name = "Building_Name_95"
                        },
                        new
                        {
                            Id = (short)96,
                            Location = "Location_96",
                            Name = "Building_Name_96"
                        },
                        new
                        {
                            Id = (short)97,
                            Location = "Location_97",
                            Name = "Building_Name_97"
                        },
                        new
                        {
                            Id = (short)98,
                            Location = "Location_98",
                            Name = "Building_Name_98"
                        },
                        new
                        {
                            Id = (short)99,
                            Location = "Location_99",
                            Name = "Building_Name_99"
                        },
                        new
                        {
                            Id = (short)100,
                            Location = "Location_100",
                            Name = "Building_Name_100"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Model.DataField", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("DataFields");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Effiency"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Power"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Model.Object", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Objects");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Chiller"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Chilled Water Pump"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Condenser Water Pump"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Cooling Tower"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "System"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Model.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("BuildingId")
                        .HasColumnType("smallint");

                    b.Property<short>("DataFieldId")
                        .HasColumnType("smallint");

                    b.Property<short>("ObjectId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
